// <auto-generated />
using System;
using EntityIntro.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityIntro.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EntityIntro.Models.Burrito", b =>
                {
                    b.Property<int>("BurritoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Beans");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("Guac");

                    b.Property<string>("Meat");

                    b.Property<string>("Name");

                    b.Property<string>("Rice");

                    b.Property<string>("Tortilla");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("Vegetable");

                    b.HasKey("BurritoId");

                    b.ToTable("Burritos");
                });
#pragma warning restore 612, 618
        }
    }
}
